version: '3'
services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile.dev # Use the development Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - .:/app
        environment:
            - CHOKIDAR_USEPOLLING=true # Enable file system polling for hot-reloading
        networks:
            - portfolio

networks:
    portfolio:
        driver: bridge